import { ShopItem, InventoryItem } from '../types';

const inventoryItems: ShopItem[] = [
  {
    id: '1',
    name: 'Cosmic Blade',
    description: 'A legendary sword forged in the depths of space. Glows with ethereal purple energy.',
    imageUrl: 'https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=400&q=80',
    price: 500,
    rarity: 'legendary',
    stock: 3,
    category: 'Weapons',
  },
  {
    id: '2',
    name: 'Stellar Shield',
    description: 'An epic shield that deflects all cosmic attacks. Reinforced with Solana energy.',
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&q=80',
    price: 300,
    rarity: 'epic',
    stock: 8,
    category: 'Armor',
  },
  {
    id: '3',
    name: 'Nebula Potion',
    description: 'A rare potion that restores all stats. Tastes like stardust.',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&q=80',
    price: 150,
    rarity: 'rare',
    stock: 20,
    category: 'Consumables',
  },
  {
    id: '4',
    name: 'Space Helmet',
    description: 'Common protective headgear for space travelers. Basic but reliable.',
    imageUrl: 'https://images.unsplash.com/photo-1617791160536-598cf32026fb?w=400&q=80',
    price: 50,
    rarity: 'common',
    stock: 50,
    category: 'Armor',
  },
  {
    id: '5',
    name: 'Quantum Gauntlets',
    description: 'Epic gloves that enhance your abilities. Made from quantum-entangled materials.',
    imageUrl: 'https://images.unsplash.com/photo-1608481337062-4093bf3ed404?w=400&q=80',
    price: 250,
    rarity: 'epic',
    stock: 12,
    category: 'Armor',
  },
  {
    id: '6',
    name: 'Crystal Amulet',
    description: 'A rare mystical amulet that provides protection. Shimmers with inner light.',
    imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&q=80',
    price: 180,
    rarity: 'rare',
    stock: 15,
    category: 'Accessories',
  },
];

export const mockInventory: InventoryItem[] = [
  {
    id: '1',
    walletAddress: 'current-user',
    item: inventoryItems[3],
    acquiredAt: '2026-03-05T10:00:00Z',
    txSignature: 'mock-signature-1',
  },
  {
    id: '2',
    walletAddress: 'current-user',
    item: inventoryItems[2],
    acquiredAt: '2026-03-06T14:30:00Z',
    txSignature: 'mock-signature-2',
  },
  {
    id: '3',
    walletAddress: 'current-user',
    item: inventoryItems[5],
    acquiredAt: '2026-03-08T09:15:00Z',
    txSignature: 'mock-signature-3',
  },
];
